### ISSUE TITLE
Send Host header with subdomain value

### ISSUE THREAD

**Issue by jasonaowen** [recursecenter/proxy#5]
Forwarded requests should have the `Host` header set to the value of the subdomain, rather than the value of the target, so that applications can properly distinguish between requests made directly to the application and requests that went through the proxy.

To confirm this behavior, I checked the headers sent by the proxy by using [this simple debugging server](https://gist.github.com/phrawzty/62540f146ee5e74ea1ab) on a machine that I control, created a subdomain through the `recurse.com` UI pointing to it, and then visited it in my browser. It printed out:

```
Host: <server ip address>:8000
Connection: close
Accept: image/webp,*/*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Cache-Control: no-cache
DNT: 1
Pragma: no-cache
User-Agent: <user agent>
X-Forwarded-For: <client ip address>
X-Forwarded-Port: 443
X-Forwarded-Proto: https
```

The `<server ip address>` is what I specified in the subdomain UI, and while the `X-Forwarded-` headers indicate a proxy is present, nothing is present to indicate to the application that it should behave as if its hostname is `subdomain.example.com` (or whatever).

For context, this is important to me in trying to configure the [Recurse Center Community Portfolio](https://github.com/jasonaowen/recurse-community-portfolio/issues); the framework I'm using needs to know its hostname to construct the OAuth redirect URIs, and fails to authenticate with the current setup.

**Comment by davidbalbert** [comment]
@jasonaowen does your framework support [`X-Forwarded-Host`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host)? That seems like the generally accepted way to deal with this.

If it does, I'll see if it's easy to add to Proxy's config.

**Comment by davidbalbert** [comment]
@jasonaowen never mind. Configuration error on our part. Just fixed it.

I'm going to close this issue. If you're still having problems, feel free to reopen.

Thanks for reporting!

**Comment by davidbalbert** [comment]
Turns out setting the `Host` header beaks a lot of things. `X-Forwarded-Host` will have to do. Proxy now sets this.

**Comment by jasonaowen** [comment]
> @jasonaowen does your framework support `X-Forwarded-Host`? That seems like the generally accepted way to deal with this.

It turns out the answer is [yes, but not by default](https://github.com/jasonaowen/recurse-community-portfolio/issues/89#issuecomment-501359739). This does seem to be the right way to deal with this - thank you so much for adding the header, @davidbalbert! I should have a fix deployed on Portfolio later today to take advantage of it.

**Comment by davidbalbert** [comment]
Glad to hear it'll work. Happy to help.
